export const accountData = {
  credit: [
    {
      id: 13,
      plaidAccountId: 'XAbm5voQVwCkdEDp3xQbcGNaLZrWRgibJ6o88',
      plaidAvailableBalance: null,
      plaidCreditLimit: '2000.00',
      plaidCurrentBalance: '410.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Credit Card',
      plaidOfficialName: 'Plaid Diamond 12.5% APR Interest Credit Card',
      plaidPersistentAccountId: null,
      plaidSubType: 'credit card',
      plaidType: 'credit',
    },
  ],
  depository: [
    {
      id: 14,
      plaidAccountId: 'DknN5Ao4zwinxrz6AJdET5BrXGywkeI3dwjGp',
      plaidAvailableBalance: '43200.00',
      plaidCreditLimit: null,
      plaidCurrentBalance: '43200.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Money Market',
      plaidOfficialName: 'Plaid Platinum Standard 1.85% Interest Money Market',
      plaidPersistentAccountId: null,
      plaidSubType: 'money market',
      plaidType: 'depository',
    },
    {
      id: 11,
      plaidAccountId: '6GnV8jXLbBUGPZEd1DJBc9ANkgE517t8k9vnk',
      plaidAvailableBalance: null,
      plaidCreditLimit: null,
      plaidCurrentBalance: '1000.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid CD',
      plaidOfficialName: 'Plaid Bronze Standard 0.2% Interest CD',
      plaidPersistentAccountId:
        '2a01484e1b5ef0b54fbcb89658b2764529bbec94a16f7b95481280a7',
      plaidSubType: 'cd',
      plaidType: 'depository',
    },
    {
      id: 1,
      plaidAccountId: 'vog1PZB3WRfwXRMV3blEiVDpd7lQgMtqJzyVg',
      plaidAvailableBalance: '100.00',
      plaidCreditLimit: null,
      plaidCurrentBalance: '110.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Checking',
      plaidOfficialName: 'Plaid Gold Standard 0% Interest Checking',
      plaidPersistentAccountId:
        '8cfb8beb89b774ee43b090625f0d61d0814322b43bff984eaf60386e',
      plaidSubType: 'checking',
      plaidType: 'depository',
    },
    {
      id: 4,
      plaidAccountId: 'RpwE5vBZy1tL6PjRZqVQieWBbRQlKjuaMle5Z',
      plaidAvailableBalance: '200.00',
      plaidCreditLimit: null,
      plaidCurrentBalance: '210.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Saving',
      plaidOfficialName: 'Plaid Silver Standard 0.1% Interest Saving',
      plaidPersistentAccountId:
        '211a4e5d8361a3afb7a3886362198c7306e00a313b5aa944c20d34b6',
      plaidSubType: 'savings',
      plaidType: 'depository',
    },
  ],
  investment: [
    {
      id: 16,
      plaidAccountId: 'VEZn5vpwygHvjoVRZ8ayUDbrWl9m5ku9lmGNL',
      plaidAvailableBalance: null,
      plaidCreditLimit: null,
      plaidCurrentBalance: '320.76',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid IRA',
      plaidOfficialName: null,
      plaidPersistentAccountId: null,
      plaidSubType: 'ira',
      plaidType: 'investment',
    },
    {
      id: 17,
      plaidAccountId: 'wkRLjM3xX5iBgDJr3ARGtw6Vvgm5dbIPMNnK4',
      plaidAvailableBalance: null,
      plaidCreditLimit: null,
      plaidCurrentBalance: '23631.98',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid 401k',
      plaidOfficialName: null,
      plaidPersistentAccountId: null,
      plaidSubType: '401k',
      plaidType: 'investment',
    },
  ],
  loan: [
    {
      id: 15,
      plaidAccountId: 'JjwZ5vkQNbfWxgKpbq6DtvBGkp84njFBx4zwz',
      plaidAvailableBalance: null,
      plaidCreditLimit: null,
      plaidCurrentBalance: '56302.06',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Mortgage',
      plaidOfficialName: null,
      plaidPersistentAccountId: null,
      plaidSubType: 'mortgage',
      plaidType: 'loan',
    },
    {
      id: 12,
      plaidAccountId: '5AnDgP7JMVCQlWD49pVRc3m8bG9kndF5Jwkjq',
      plaidAvailableBalance: null,
      plaidCreditLimit: null,
      plaidCurrentBalance: '65262.00',
      plaidIsoCurrencyCode: 'USD',
      plaidName: 'Plaid Student Loan',
      plaidOfficialName: null,
      plaidPersistentAccountId: null,
      plaidSubType: 'student',
      plaidType: 'loan',
    },
  ],
};
